logging.level.root=info

# Key Management
#trecauth.app=Message-Notify
trecauth.jwt.rsa.public-key-name=${TREC_PUBLIC_KEY}
trecauth.jwt.rsa.private-key-name=${TREC_PRIVATE_KEY}

# Messaging app Uses MongoDB
spring.data.mongodb.uri=${MONGO_CONNECTION}

# Mongo Support in Spring Boot 4
spring.mongodb.uri=${MONGO_CONNECTION}


spring.cassandra.contact-points=${CASSANDRA_CONTACT}
spring.cassandra.port=${CASSANDRA_PORT}
spring.cassandra.username=${CASSANDRA_USERNAME}
spring.cassandra.password=${CASSANDRA_PASSWORD}


spring.cassandra.local-datacenter=Central US


# Notify sending

# Use 'azure-service-bus-entra' or 'azure-service-bus-connection-string'
trecapps.notify.producer.strategy=${NOTIFY_PRODUCER_STRATEGY}
trecapps.notify.producer.queue=notify
trecapps.notify.producer.connection=${NOTIFY_PRODUCER_CONN}
trecapps.notify.producer.namespace=${NOTIFY_PRODUCER_NAMESPACE}