trecauth.refresh.domain=test.trecapps.com

# Establish how to get the keys for JWT Auth token signing and validation
trecauth.jwt.key-storage.strategy=AKV-cred

trec.jwt.vault-name=trecappstestvault
trecauth.jwt.strategy=RSA
trecauth.jwt.rsa.public-key-name=trec-2022-pub
trecauth.jwt.rsa.private-key-name=trec-2022-priv-v8

trec.jwt.tenantId=${KV_TENANT}
trec.jwt.clientId=${KV_CLIENT_ID}
trec.jwt.clientSecret=${KV_CLIENT_SECRET}


# For Field Encryption
trecauth.encryption.strategy=RSA
trecauth.encrypt.rsa.public-key-name=tc-field-pub
trecauth.encrypt.rsa.private-key-name=tc-field-priv

trecauth.encryptor.key-storage.strategy=AKV-cred
trec.encryptor.vault-name=trecappstestvault
trec.encryptor.tenantId=${KV_TENANT}
trec.encryptor.clientId=${KV_CLIENT_ID}
trec.encryptor.clientSecret=${KV_CLIENT_SECRET}


#Scheduling for Key Rotation
trecauth.rotate.do-rotate=true
trecauth.rotate.rotate-cron-schedule=0 0 2 ? * SUN *
trecauth.key.version-count=2


spring.cassandra.schema-action=create_if_not_exists
