logging.level.root=info

spring.main.allow-bean-definition-overriding=true

# Force a WebFlux Netty environment
spring.main.web-application-type=reactive

# Key Management
#trecauth.app=Message-Notify
trecauth.jwt.rsa.public-key-name=${TREC_PUBLIC_KEY}
trecauth.jwt.rsa.private-key-name=${TREC_PRIVATE_KEY}

# Set up MongoDB
trecapps.mongo.sm.uri=${MONGO_URI}
trecapps.sm.repo.strategy=mongo-uri
# Set up Mongo Repository for Account storage
trecauth.account.repo.strategy=mongo-uri

trecauth.mongo.account.uri=${MONGO_URI}
trecauth.mongo.account.database=tc-accounts


spring.cassandra.contact-points=${CASSANDRA_CONTACT}
spring.cassandra.port=${CASSANDRA_PORT}
spring.cassandra.username=${CASSANDRA_USERNAME}
spring.cassandra.password=${CASSANDRA_PASSWORD}


spring.cassandra.local-datacenter=Central US


# Notify sending

# Use 'azure-service-bus-entra' or 'azure-service-bus-connection-string'
trecapps.notify.producer.strategy=${NOTIFY_PRODUCER_STRATEGY}
trecapps.notify.producer.queue=notify
trecapps.notify.producer.connection=${NOTIFY_PRODUCER_CONN}
trecapps.notify.producer.namespace=${NOTIFY_PRODUCER_NAMESPACE}